# Generated by Django 5.2.7 on 2025-10-06 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this itinerary')),
                ('is_public', models.BooleanField(default=False, help_text='Make visible to others')),
                ('share_token', models.CharField(blank=True, help_text='Token for sharing via link', max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Order in the itinerary')),
                ('note', models.TextField(blank=True, help_text='Personal note for this stop')),
                ('planned_start', models.DateTimeField(blank=True, help_text='Planned arrival time', null=True)),
                ('planned_end', models.DateTimeField(blank=True, help_text='Planned departure time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itineraries.itinerary')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='locations.location')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
                'unique_together': {('itinerary', 'location')},
            },
        ),
    ]
