# Generated by Django 5.2.7 on 2025-10-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itinerarystop",
            name="visit_time",
            field=models.TimeField(
                blank=True, help_text="Planned visit time for this location", null=True
            ),
        ),
    ]
