# Generated by Django 5.2.7 on 2025-10-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("itineraries", "0002_make_visit_time_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="date",
            field=models.DateField(
                blank=True, help_text="Planned date for this itinerary", null=True
            ),
        ),
    ]
