# Generated by Django 5.2.7 on 2025-10-29 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_directchat_directmessage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectChatLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("left_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="events.directchat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_leaves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-left_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-left_at"],
                        name="events_dire_user_id_102b26_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chat", "user"), name="uniq_chat_leave"
                    )
                ],
            },
        ),
    ]
