# Generated by Django 4.2.25 on 2025-10-07 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicArt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=500, null=True)),
                ("borough", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("medium", models.CharField(blank=True, max_length=300, null=True)),
                ("dimensions", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "year_created",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "year_dedicated",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("agency", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "community_board",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Public Art",
                "verbose_name_plural": "Public Art Pieces",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="UserFavoriteArt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "art",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="loc_detail.publicart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_art",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "unique_together": {("user", "art")},
            },
        ),
    ]
