# Generated by Django 4.2.25 on 2025-10-07 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loc_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='loc_detail.publicart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
