# Generated by Django 5.2.7 on 2025-10-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loc_detail", "0003_publicart_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicart",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
