# Generated by Django 5.2.7 on 2025-10-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loc_detail", "0004_alter_publicart_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicart",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
