# Generated by Django 4.2.25 on 2025-10-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loc_detail", "0005_alter_publicart_image"),
        ("loc_detail", "0006_add_ratings_and_replies"),
    ]

    operations = []
