# Generated by Django 4.2.25 on 2025-10-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loc_detail", "0007_merge_20251027_1455"),
    ]

    operations = [
        migrations.AddField(
            model_name="artcomment",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a photo of the artwork",
                null=True,
                upload_to="review_images/",
            ),
        ),
    ]
