# Generated by Django 5.2.7 on 2025-11-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loc_detail", "0008_artcomment_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicart",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="public_art/thumbnails/",
            ),
        ),
    ]
