# Generated by Django 5.2.7 on 2025-11-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loc_detail", "0009_publicart_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicart",
            name="thumbnail",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to=""
            ),
        ),
    ]
