# Generated by Django 4.2.25 on 2025-10-27 02:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userfollow",
            name="unique_follow",
        ),
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together={("follower", "following")},
        ),
    ]
